n1 = int(input("Primeiro número: "))
n2 = int(input("Segundo número: "))

print("\n{} + {} = {}".format(n1, n2, n1+n2))
print("\n{} - {} = {}".format(n1, n2, n1-n2))
print("\n{} * {} = {}".format(n1, n2, n1*n2))
print("\n{} / {} = {}".format(n1, n2, n1/n2))
print("\n{} // {} = {}".format(n1, n2, n1//n2))
print("\n{} % {} = {}".format(n1, n2, n1 % n2))
print("\n{}^{} = {}".format(n1, n2, n1 ** n2))
